# Generated by Django 2.0.5 on 2018-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.PositiveIntegerField(max_length=255)),
                ('email', models.TextField(null=True)),
                ('address', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cateId',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='create_user',
            field=models.CharField(default='没有名字', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='暂无内容', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='没有名字', max_length=255),
        ),
    ]
