# Generated by Django 2.0.5 on 2018-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180705_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='没有名字', max_length=255)),
                ('userId', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
