# Generated by Django 2.0.6 on 2018-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.PositiveIntegerField(),
        ),
    ]
